In [2]:
from layers import *
import tensorflow as tf

In [5]:
from layers import *
import tensorflow as tf

bs=64
field_num=23
emb_size=16
inputs=tf.ones((bs,field_num,emb_size))
MLP(out_dim=3,hidden_units=[128,64])(inputs)
SELayer([128])(inputs)

## Dinattention
query=tf.ones((bs,emb_size))
key=tf.ones((bs,10,emb_size))
seqlen=tf.ones((bs))*5
DinAttention()(key,query,seqlen)

## ppnet
inputs=tf.ones((bs,1288))
gate_emb=tf.ones((bs,128))
PPNetLayer(out_dim=64,hidden_units=[128],gate_hidden_units=[128,128])(inputs,gate_emb)

## fibi
inputs=tf.ones((64,23,16))
BilinearInteraction()(inputs)

## cin
inputs=tf.ones((64,23,16))
CinLayer([128,128])(inputs)

## Fm
inputs=tf.ones((64,23,16))
FMCrossLayer()(inputs)

## MMoE
inputs=tf.ones((bs,1288))
MMoELayer(4,[256],2,[128])(inputs)

## PLE
inputs=tf.ones((bs,1288))
PLELayer(1,4,[256],2,[128],1)(inputs)


[<tf.Tensor: shape=(64, 256), dtype=float32, numpy=
 array([[0.09439056, 0.4682368 , 0.14988433, ..., 0.5949478 , 0.5036044 ,
         0.57740164],
        [0.09439056, 0.4682368 , 0.14988433, ..., 0.5949478 , 0.5036044 ,
         0.57740164],
        [0.09439056, 0.4682368 , 0.14988433, ..., 0.5949478 , 0.5036044 ,
         0.57740164],
        ...,
        [0.09439056, 0.4682368 , 0.14988433, ..., 0.5949478 , 0.5036044 ,
         0.57740164],
        [0.09439044, 0.46823692, 0.14988431, ..., 0.5949477 , 0.5036043 ,
         0.57740164],
        [0.09439044, 0.46823692, 0.14988431, ..., 0.5949477 , 0.5036043 ,
         0.57740164]], dtype=float32)>,
 <tf.Tensor: shape=(64, 256), dtype=float32, numpy=
 array([[0.06685781, 0.483452  , 0.1261303 , ..., 1.3969997 , 0.4793982 ,
         0.34164172],
        [0.06685781, 0.483452  , 0.1261303 , ..., 1.3969997 , 0.4793982 ,
         0.34164172],
        [0.06685781, 0.483452  , 0.1261303 , ..., 1.3969997 , 0.4793982 ,
         0.34164172],
 

In [63]:
a=tf.ones((64,12))
b=tf.ones((64,12))


In [67]:
inputs=tf.ones((64,23,16))
obj=BilinearInteraction()
obj(inputs)

253 23


<tf.Tensor: shape=(64, 253, 16), dtype=float32, numpy=
array([[[-1.4013947 , -1.7496046 ,  0.16214529, ..., -0.00360952,
          1.4629452 , -0.9206601 ],
        [ 0.63977605, -0.08518679, -1.070574  , ..., -0.27574095,
          1.4065473 , -0.88943446],
        [ 1.4094085 ,  0.5798226 , -0.78099006, ..., -1.602323  ,
         -0.9113116 ,  0.8146272 ],
        ...,
        [-1.7533984 ,  0.5607278 , -1.5570295 , ...,  0.4228723 ,
         -0.5006953 , -0.37363836],
        [-0.33253673,  0.80279505, -0.00845532, ...,  2.1672962 ,
          0.6889852 ,  0.852971  ],
        [ 0.274296  , -1.5495188 , -0.55503577, ..., -1.2353386 ,
          0.00488108,  0.5857283 ]],

       [[-1.4013947 , -1.7496046 ,  0.16214529, ..., -0.00360952,
          1.4629452 , -0.9206601 ],
        [ 0.63977605, -0.08518679, -1.070574  , ..., -0.27574095,
          1.4065473 , -0.88943446],
        [ 1.4094085 ,  0.5798226 , -0.78099006, ..., -1.602323  ,
         -0.9113116 ,  0.8146272 ],
        ...,

In [20]:
a=tf.ones((64,12,16))
b=tf.concat([tf.ones((1,16,16))*i for i in range(12)],axis=0)
ans=tf.einsum("ijk,jkk->ijk",a,b)

In [21]:
ans.shape

TensorShape([64, 12, 16])

In [30]:
import itertools
n=3
for i,j in itertools.combinations(range(n), 2):
    print(i,j)

0 1
0 2
1 2
